networks:
  short-network:

services:
  short:
    image: thek4n/short
    build: .
    container_name: 'short'
    ports:
      - 8080:80
    networks:
      - short-network
    environment:
      REDIS_HOST: 'short-redis'
    restart: always

  redis:
    image: redis
    container_name: 'short-redis'
    networks:
        - short-network
    restart: always
